### ISSUE TITLE
Entity Distance Not being Raised properly sometimes.

### ISSUE THREAD

**Issue by ezraoctopus** [jan-leila/sodium-fabric#4]
### Version Information

> sodium-1.16.1-backport-fabric-0.2.1+build.9.jar

### Expected Behavior

>When I increase my entity distance from 50 to 500 it should actually increase.

### Actual Behavior

>Sometimes it does not actually increase when I move the slider. 

### Reproduction Steps

> I have no effective way of reproducing. It happens about 1/5 times I enter the nether on 500%, given I reset on 50%.

### System Information

> - Java Version: 17
> - CPU: Ryzen 9 5900x
> - GPU: Rtx 3060 ti

### Other Information

All legal mods used except voyager, krypton, and WorldPreview. All mods updated.
Example:
The run starts on 50% and I put it to 500% around 10 seconds into the run.

https://youtu.be/8JCTjwKG8Cc

**Comment by jan-leila** [comment]
this should fix it https://github.com/jan-leila/sodium-fabric/pull/5
